language: java

dist: xenial

jdk:
  - openjdk11
  - openjdk-ea

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V -q

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

notifications:
    email:
        on_success: never
        on_failure: never
    slack:
        on_failure: change
        on_success: change
        rooms:
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/generic-display
        branch: master
        jdk: openjdk11
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/generic-display
        tags: true
        jdk: openjdk11
